version: '3'
services:
  ghost:
    image: ghost:1-alpine
    ports:
      - 2368:2368
    depends_on:
      - "db"
    networks:
      - my-network
    environment:
      database__client: mysql
      database__connection__host: db
      database__connection__user: root
      database__connection__password: password
      database__connection__database: ghost
  db:
    image: mysql:5.7
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - my-network
    environment:
      MYSQL_ROOT_PASSWORD: password
volumes:
  db-data:

networks:
  my-network: